#!/bin/bash

IP=$(ifconfig eth0 | awk '/inet/{print substr($2,1)}')

rm -rf /run/httpd/* /tmp/httpd* 

sed -i "s/Listen.*.80/Listen $IP:80/g" /etc/httpd/conf/httpd.conf
sed -i "s/#DocumentRoot/DocumentRoot/g" /etc/httpd/conf.d/ssl.conf
sed -i "s/Listen 443/Listen $IP:443/g" /etc/httpd/conf.d/ssl.conf
sed -i "s/;date.timezone =/date.timezone = America\/Sao_Paulo/" /etc/php.ini
sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php.ini
sed -i "s/expose_php = On/expose_php = Off/" /etc/php.ini
sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 10M/" /etc/php.ini

rm /etc/localtime
ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

exec /usr/sbin/apachectl -DFOREGROUND
