apiVersion: v1
kind: Service
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  type: NodePort
  selector:
    app: {{POD_NAME}}
  ports:
    - protocol: TCP
      nodePort: {{NODE_PORT}}
      port: 80
      targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{POD_NAME}}
  template:
    metadata:
      labels:
        app: {{POD_NAME}}
    spec:
      containers:
      - name: workloadapp
        readinessProbe:
          periodSeconds: 2
          httpGet:
            path: /health.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        image: pmoritz/workloadapp:1.1.12
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
      {{SCHEDULER}}
      {{NODE_NAME}}
