apiVersion: v1
kind: Service
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  type: NodePort
  selector:
    app: {{POD_NAME}}
  ports:
    - protocol: TCP
      nodePort: {{NODE_PORT}}
      port: 3000
      targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{POD_NAME}}
  template:
    metadata:
      labels:
        app: {{POD_NAME}}
    spec:
      containers:
      - name: workloadapp
        image: registry.k8s.io/hpa-example
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
      {{SCHEDULER}}
