apiVersion: v1
kind: Service
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  type: NodePort
  selector:
    app: {{POD_NAME}}
  ports:
    - protocol: TCP
      nodePort: {{NODE_PORT}}
      port: 80
      targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{POD_NAME}}
  template:
    metadata:
      labels:
        app: {{POD_NAME}}
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4.3-php8.2-apache
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: '143.198.161.106:16398'
          - name: WORDPRESS_DB_PASSWORD
            value: 'AVNS_UarevlHO3kq6eyf8LH0'
          - name: WORDPRESS_DB_USER
            value: 'avnadmin'
          - name: WORDPRESS_DB_NAME
            value: {{POD_NAME}}
      {{SCHEDULER}}
      {{NODE_NAME}}
