apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: lab1
spec:
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1", "--verbose"]
