apiVersion: v1
kind: Service
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  type: NodePort
  selector:
    app: {{POD_NAME}}
  ports:
    - protocol: TCP
      nodePort: {{NODE_PORT}}
      port: 8080
      targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{POD_NAME}}
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{POD_NAME}}
  template:
    metadata:
      labels:
        app: {{POD_NAME}}
    spec:
      containers:
      - name: customapp
        image: pedromoritz/customapp:latest
        ports:
          - name: http
            containerPort: 8080
      {{CUSTOM_SCHEDULER}}
