apiVersion: v1
kind: Service
metadata:
  name: pod2
  namespace: lab1
spec:
  type: NodePort
  selector:
    app: pod2
  ports:
    - protocol: TCP
      nodePort: 31002
      port: 8080
      targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2
  namespace: lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
      - name: customapp
        image: pedromoritz/customapp:latest
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            memory: "3Gi"
            cpu: "500m"