apiVersion: v1
kind: Service
metadata:
  name: target-pod-custom-scheduler
  namespace: lab1
spec:
  type: NodePort
  selector:
    app: target-pod-custom-scheduler
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-pod-custom-scheduler
  namespace: lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-pod-custom-scheduler
  template:
    metadata:
      labels:
        app: target-pod-custom-scheduler
    spec:
      schedulerName: ppgcc_balancer
      containers:
      - name: httpd
        image: httpd:latest
        ports:
          - name: http
            containerPort: 80
